routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard.index');

    // profile
    Route::get('/profile', 'HomeController@profile')->name('user.profile');
    Route::post('/profile', 'HomeController@editProfile')->name('user.editProfile');

    // end profile

    // sliders routes
    Route::get('sliders-data', 'SliderController@data')->name('sliders.data');
    Route::post('sliders-bulkDelete', 'SliderController@bulkDelete')->name('sliders.bulkDelete');
    Route::resource('sliders', 'SliderController')->except('show');
    //end sliders routes

    // about routes
    Route::get('about-data', 'AboutController@data')->name('about.data');
    Route::post('about-bulkDelete', 'AboutController@bulkDelete')->name('about.bulkDelete');
    Route::resource('about', 'AboutController')->except('show');
    //end about routes

    // customers routes
    Route::get('customers-data', 'CustomerController@data')->name('customers.data');
    Route::post('customers-bulkDelete', 'CustomerController@bulkDelete')->name('customers.bulkDelete');
    Route::resource('customers', 'CustomerController')->except('show');
    //end customers routes

    // blogs routes
    Route::get('blogs-data', 'BlogController@data')->name('blogs.data');
    Route::post('blogs-bulkDelete', 'BlogController@bulkDelete')->name('blogs.bulkDelete');
    Route::resource('blogs', 'BlogController')->except('show');
    //end customers routes

    // services routes
    Route::get('services-data', 'ServiceController@data')->name('services.data');
    Route::post('services-bulkDelete', 'ServiceController@bulkDelete')->name('services.bulkDelete');
    Route::resource('services', 'ServiceController')->except('show');
    //end customers routes

    // umras routes
    Route::get('umras-data', 'UmraController@data')->name('umras.data');
    Route::post('umras-bulkDelete', 'UmraController@bulkDelete')->name('umras.bulkDelete');
    Route::resource('umras', 'UmraController')->except('show');
    //end customers routes


    // projects routes
    Route::get('contact-us-data', 'ContactUsController@data')->name('contact-us.data');
    Route::post('contact-us-bulkDelete', 'ContactUsController@bulkDelete')->name('contact-us.bulkDelete');
    Route::resource('contact-us', 'ContactUsController')->except('show');
    //end customers routes

    // settings
    Route::get('settings', 'SettingController@index')->name('settings.index');
    Route::post('settings', 'SettingController@store')->name('settings.store');
    // end settings

    //pages
    Route::get('pages-data', 'PageController@data')->name('pages.data');
    Route::resource('pages', 'PageController')->except('show');
    //end pages


    // bookings
    Route::get('bookings/data', 'BookingController@data')->name('bookings.data');
    Route::post('bookings-bulkDelete', 'BookingController@bulkDelete')->name('bookings.bulkDelete');
    Route::resource('bookings', 'BookingController');
    // end bookings



});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::namespace('Website')->group(function () {

    // home
    Route::get('/', 'FrontController@index')->name('home');
    // end home

    // about
    Route::get('about', 'AboutController@index');
    // end about

    // services
    Route::get('services', 'ServiceController@index');
    Route::get('services/{id}', 'ServiceController@show');
    // end services

    // projects
    Route::get('projects', 'ProjectController@index');
    Route::get('projects/{id}', 'ProjectController@show');
    // end projects

    // blogs
    Route::get('blogs', 'BlogController@index');
    Route::get('blogs/{id}', 'BlogController@show');
    // end blogs

    //contact us
    Route::view('contact-us', 'website.pages.contact_us.index');
    Route::post('contact-us', 'ContactUsController@post')->name('website.contactUs');
    // end contact us

    // umra
    Route::get('umra', 'UmraController@index');
    Route::get('umra/{id}', 'UmraController@show');
    Route::post('umra/booking', 'UmraController@booking')->name('umra.booking');
    // end umra

    Route::get('contact-us','ContactUsController@index');
    Route::post('contact-us','ContactUsController@post')->name('contact_us.save');

});

resources/views/dashboard/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">
                <div class="row row-sm">
                    <div class="col-12 col-sm-6 col-md-6 col-xl-3">
                        <a href="{{route('blogs.index')}}" class="card custom-card">
                            <div class="card-body">
                                <div class="card-item">
                                    <div class="card-item-icon card-icon">
                                        <img src="{{asset('assets/dashboard')}}/img/analysis.png" alt="">
                                    </div>
                                    <div class="card-item-title mb-2"><label
                                            class="main-content-label tx-13 font-weight-bold mb-1">عدد المقالات</label>

                                    </div>
                                    <div class="card-item-body">
                                        <div class="card-item-stat">
                                            <h4 class="font-weight-bold">{{$data['blogs_count']}}</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-12 col-sm-6 col-md-6 col-xl-3">
                        <a href="{{route('customers.index')}}" class="card custom-card">
                            <div class="card-body">
                                <div class="card-item">
                                    <div class="card-item-icon card-icon">
                                        <img src="{{asset('assets/dashboard')}}/img/analysis.png" alt="">
                                    </div>
                                    <div class="card-item-title mb-2"><label
                                            class="main-content-label tx-13 font-weight-bold mb-1">عدد العملاء</label>

                                    </div>
                                    <div class="card-item-body">
                                        <div class="card-item-stat">
                                            <h4 class="font-weight-bold">{{$data['customers_count']}}</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-12 col-sm-6 col-md-6 col-xl-3">
                        <a href="{{route('services.index')}}" class="card custom-card">
                            <div class="card-body">
                                <div class="card-item">
                                    <div class="card-item-icon card-icon">
                                        <img src="{{asset('assets/dashboard')}}/img/analysis.png" alt="">
                                    </div>
                                    <div class="card-item-title  mb-2"><label
                                            class="main-content-label tx-13 font-weight-bold mb-1">عدد الخدمات</label>

                                    </div>
                                    <div class="card-item-body">
                                        <div class="card-item-stat">
                                            <h4 class="font-weight-bold">{{$data['services_count']}}</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                    <div class="col-12 col-sm-6 col-md-6 col-xl-3">
                        <a href="{{route('umras.index')}}" class="card custom-card">
                            <div class="card-body">
                                <div class="card-item">
                                    <div class="card-item-icon card-icon">
                                        <img src="{{asset('assets/dashboard')}}/img/analysis.png" alt="">
                                    </div>
                                    <div class="card-item-title  mb-2"><label
                                            class="main-content-label tx-13 font-weight-bold mb-1">عدد العمرات</label>

                                    </div>
                                    <div class="card-item-body">
                                        <div class="card-item-stat">
                                            <h4 class="font-weight-bold">{{$data['umras_count']}}</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>

                </div>
                <div class="card">
                    <div class="card-header">
                        <h3>المستخدمين</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div id="chart3" class="chart"></div>
                            </div>
                            <div class="col-md-6">
                                <div id="chart4" class="chart"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End Main Content-->
@endsection
@push('js')
    <script>
        $(function () {
            $('.datepicker').daterangepicker({
                locale: {
                    format: 'DD/MM/YYYY'
                },
                singleDatePicker: true,
                showDropdowns: true,
                autoApply: true,
                opens: 'left',
                minYear: 2010
            });
        });

    </script>
    <script>
        $(document).ready(function () {

            table.buttons().container()
                .appendTo('#DataTables_Table_0_wrapper .col-md-6:eq(0)');
        });

    </script>
    <script>
        $(document).ready(function () {
            $('.select2').select2({
                searchInputPlaceholder: 'ابحث هنا',
                width: '100%'
            });
            $('.select2-modal').select2({
                searchInputPlaceholder: 'ابحث هنا',
                width: '100%',
                dropdownParent: $(".modal")
            });
        });

    </script>
    <script>
        $('.input-images').imageUploader();

    </script>
    <script>
        $(document).ready(function () {
            $('.magnific-img').magnificPopup({
                type: 'image',
                closeOnContentClick: true,
                closeBtnInside: false,
                fixedContentPos: true,
                mainClass: 'mfp-no-margins mfp-with-zoom',
                image: {
                    verticalFit: true
                },
                zoom: {
                    enabled: true,
                    duration: 500
                }
            });
        });

    </script>
    <script>
        var myChart = echarts.init(document.getElementById('chart3'));
        option = {
            tooltip: {
                trigger: 'axis',
                axisPointer: {
                    type: 'shadow'
                },
                textStyle: {
                    fontFamily: 'Bahij_Plain'
                }
            },
            legend: {
                // bottom: 0,
                textStyle: {
                    fontSize: 16,
                    fontFamily: 'Bahij_Plain'
                }
            },
            grid: {
                left: '3%',
                right: '4%',
                bottom: '3%',
                containLabel: true
            },
            xAxis: [{
                type: 'category',
                data: ['احصائيات', 'احصائيات', 'احصائيات', 'احصائيات', 'احصائيات'],
                axisLabel: {
                    textStyle: {
                        fontSize: 15,
                        fontFamily: 'Bahij_Plain'
                    }
                }
            }],
            yAxis: [{
                type: 'value'
            }],
            series: [{
                name: 'نشط',
                type: 'bar',
                stack: 'Ad',
                data: [320, 332, 301, 334, 390],
                color: '#129d90'
            },
                {
                    name: 'غير نشط',
                    type: 'bar',
                    stack: 'Ad',
                    data: [120, 132, 101, 134, 90],
                    color: '#FFAE00'
                }
            ]
        };

        myChart.setOption(option);

    </script>
    <script>
        var myChart = echarts.init(document.getElementById('chart4'));
        var colorPalette = ['#129d90', '#FFAE00', '#00BEEC'];
        option = {
            tooltip: {
                trigger: 'item',
                textStyle: {
                    fontFamily: 'Bahij_Plain'
                }
            },
            series: [{
                type: 'pie',
                radius: ['40%', '70%'],
                avoidLabelOverlap: false,
                itemStyle: {
                    borderRadius: 10,
                    borderColor: '#fff',
                    borderWidth: 2
                },
                label: {
                    textStyle: {
                        fontFamily: 'Bahij_Plain',
                        fontSize: '20'
                    }
                },
                emphasis: {
                    label: {
                        fontWeight: 'bold'
                    }
                },
                labelLine: {
                    show: true
                },
                data: [{
                    value: 1048,
                    name: 'نشط'
                },
                    {
                        value: 735,
                        name: 'غير نشط'
                    },
                    {
                        value: 580,
                        name: 'محذوف'
                    }
                ],
                color: colorPalette
            }],
            graph: {
                color: colorPalette
            }
        };
        myChart.setOption(option);

    </script>
@endpush