routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard.index');

    // profile
    Route::get('/profile', 'HomeController@profile')->name('user.profile');
    Route::post('/profile', 'HomeController@editProfile')->name('user.editProfile');

    // end profile

    // sliders routes
    Route::get('sliders-data', 'SliderController@data')->name('sliders.data');
    Route::post('sliders-bulkDelete', 'SliderController@bulkDelete')->name('sliders.bulkDelete');
    Route::resource('sliders', 'SliderController')->except('show');
    //end sliders routes

    // about routes
    Route::get('about-data', 'AboutController@data')->name('about.data');
    Route::post('about-bulkDelete', 'AboutController@bulkDelete')->name('about.bulkDelete');
    Route::resource('about', 'AboutController')->except('show');
    //end about routes

    // customers routes
    Route::get('customers-data', 'CustomerController@data')->name('customers.data');
    Route::post('customers-bulkDelete', 'CustomerController@bulkDelete')->name('customers.bulkDelete');
    Route::resource('customers', 'CustomerController')->except('show');
    //end customers routes

    // blogs routes
    Route::get('blogs-data', 'BlogController@data')->name('blogs.data');
    Route::post('blogs-bulkDelete', 'BlogController@bulkDelete')->name('blogs.bulkDelete');
    Route::resource('blogs', 'BlogController')->except('show');
    //end customers routes

    // services routes
    Route::get('services-data', 'ServiceController@data')->name('services.data');
    Route::post('services-bulkDelete', 'ServiceController@bulkDelete')->name('services.bulkDelete');
    Route::resource('services', 'ServiceController')->except('show');
    //end customers routes

    // umras routes
    Route::get('umras-data', 'UmraController@data')->name('umras.data');
    Route::post('umras-bulkDelete', 'UmraController@bulkDelete')->name('umras.bulkDelete');
    Route::resource('umras', 'UmraController')->except('show');
    //end customers routes


    // projects routes
    Route::get('contact-us-data', 'ContactUsController@data')->name('contact-us.data');
    Route::post('contact-us-bulkDelete', 'ContactUsController@bulkDelete')->name('contact-us.bulkDelete');
    Route::resource('contact-us', 'ContactUsController')->except('show');
    //end customers routes

    // settings
    Route::get('settings', 'SettingController@index')->name('settings.index');
    Route::post('settings', 'SettingController@store')->name('settings.store');
    // end settings

    //pages
    Route::get('pages-data', 'PageController@data')->name('pages.data');
    Route::resource('pages', 'PageController')->except('show');
    //end pages


    // bookings
    Route::get('bookings/data', 'BookingController@data')->name('bookings.data');
    Route::post('bookings-bulkDelete', 'BookingController@bulkDelete')->name('bookings.bulkDelete');
    Route::resource('bookings', 'BookingController');
    // end bookings



});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::namespace('Website')->group(function () {

    // home
    Route::get('/', 'FrontController@index')->name('home');
    // end home

    // about
    Route::get('about', 'AboutController@index');
    // end about

    // services
    Route::get('services', 'ServiceController@index');
    Route::get('services/{id}', 'ServiceController@show');
    // end services

    // projects
    Route::get('projects', 'ProjectController@index');
    Route::get('projects/{id}', 'ProjectController@show');
    // end projects

    // blogs
    Route::get('blogs', 'BlogController@index');
    Route::get('blogs/{id}', 'BlogController@show');
    // end blogs

    //contact us
    Route::view('contact-us', 'website.pages.contact_us.index');
    Route::post('contact-us', 'ContactUsController@post')->name('website.contactUs');
    // end contact us

    // umra
    Route::get('umra', 'UmraController@index');
    Route::get('umra/{id}', 'UmraController@show');
    Route::post('umra/booking', 'UmraController@booking')->name('umra.booking');
    // end umra

    Route::get('contact-us','ContactUsController@index');
    Route::post('contact-us','ContactUsController@post')->name('contact_us.save');

});

app/Models/Umra.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Umra extends Model
{
    protected $table = 'umras';
    protected $guarded = [];
    protected $appends = ['image'];

    public function photo()
    {
        return $this->morphOne(Photo::class, 'photoable');
    }//end of photos function

    public function getImageAttribute()
    {

        if ($this->photo == '') {
            return asset('default.svg');
        }

        return asset('images/umras/' . $this->photo->src);


    }//end of getImageAttribute function
}

app/Http/Controllers/UmraController.php
<?php

namespace App\Http\Controllers;

use App\Helper\UploadTrait;
use App\Http\Requests\UmraRequest;
use App\Models\Umra;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class UmraController extends Controller
{
    use UploadTrait;

    public function index()
    {

        return view('dashboard.umras.index');
    }


    public function create()
    {
        return view('dashboard.umras.create');
    }

    public function data()
    {
        $model = 'umras';
        $Umras = Umra::with('photo')->get();
        return DataTables::of($Umras)
            ->addColumn('check_item', function ($raw) {
                return '<input type="checkbox" name="items[]" class="check_item" value="' . $raw->id . '">';
            })
            ->addcolumn('actions', function ($raw) use ($model) {

                return view('dashboard.includes.actions', compact('raw', 'model'));
            })
            ->rawColumns(['check_item' => 'check_item'])
            ->make(true);

    }//end of data function


    public function store(UmraRequest $request)
    {

        $data = $request->validated();


        unset($data['photo']);


        $Umra = Umra::create($data);

        if ($request->hasFile('photo')) {
            $photo = $this->upload($request->photo, 'umras');
            $Umra->photo()->create([
                'src' => $photo,
                'type' => 'Umra',
            ]);

        };

        return redirect()->route('umras.index')->with('success', 'تم إضافه البيانات بنجاح');

    }


    public function edit(Umra $umra)
    {
        return view('dashboard.umras.edit', compact('umra'));
    }

    public function update(UmraRequest $request, Umra $umra)
    {

        $data = $request->validated();
        unset($data['photo']);
        $umra->update($data);

        if ($request->hasFile('photo')) {
            $photo = $this->upload($request->photo, 'umras');
            $umra->photo ? $this->deleteOldPhoto('images/umras/', $umra->photo->src)
                & $umra->photo()->update(['src' => $photo]) : $umra->photo()->create(['src' => $photo, 'type' => 'Umra']);
        }

        return redirect()->route('umras.index')->with('success', 'تم تعديل البيانات بنجاح');
    }


    public function destroy(Umra $Umra)
    {
        $Umra->photo ? $this->deleteOldPhoto('images/umras/', $Umra->photo->src) & $Umra->photo()->delete() : '';
        Umra::destroy($Umra->id);
        return redirect()->route('umras.index')->with('success', 'تم حذف البيانات بنجاح');
    }

    public function bulkDelete(Request $request)
    {
        foreach ($request->items as $item) {
            $Umra = Umra::findOrFail($item);
            $this->destroy($Umra);
        }
        Umra::destroy($request->items);
        return redirect()->route('umras.index')->with('success', 'تم حذف البيانات بنجاح');


    }//end of bulkDelete function


}

app/Http/Controllers/Website/UmraController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Models\Booking;
use App\Models\Page;
use App\Models\Umra;
use Illuminate\Http\Request;

class UmraController extends Controller
{
    public function index()
    {
        $page_name = Page::where('url', '/umra')->first()->name;
        $umras = Umra::with('photo')->get();
        return view('website.pages.umra.index', compact('umras', 'page_name'));
    }//end of index function

    public function show($id)
    {
        $umra = Umra::findOrFail($id);
        $page_name = Page::where('url', '/umra')->first()->name;
        return view('website.pages.umra.show', compact('umra', 'page_name'));
    }//end of show function

    public function booking(Request $request)
    {

       $data =  $request->validate([
            'umra_id'=>'required|exists:umras,id',
            'name'=>'required|string',
            'email'=>'required|email',
            'phone'=>'required',
            'country'=>'required|string',
        ]);

       Booking::create($data);

       return redirect()->back()->with('success','تم حجز عمرتك بنجاح');
    }//end of booking function
}

resources/views/dashboard/umras/create.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">

                <form action="{{route('umras.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                        <div class="card-header">
                            <h3>إضافه عمره</h3>
                        </div>
                        <div class="card-body pb-0">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input value="{{old('name')}}" type="text" name="name" class="form-control">
                                        <span class="input-span">اسم العمره</span>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <textarea name="details" rows="3" class="form-control editor">{{old('details')}}</textarea>
                                        <span class="input-span">تفاصيل العمره</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input type="date" value="{{old('start_at')}}" name="start_at" class="form-control">
                                        <span class="input-span">تاريخ الانطلاق</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input type="number" min="0" value="{{old('price')}}" name="price" class="form-control">
                                        <span class="input-span">سعر العمره</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <label class="">الصورة ( مقاس الصورة -- 750 طول * 1660 عرض )</label>
                                        <input id="photo" type="file" name="photo">
                                        <img width="100" id="preview" height="100" src="{{asset('default.svg')}}" alt="">
                                    </div>

                                </div>


                            </div>

                            <div class="accordion-container">
                                <div class="set">
                                    <a href="#">
                                        بيانات السيو SEO
                                        <i class="fa fa-plus"></i>
                                    </a>
                                    <div class="box-custom">
                                        <div class="flex-divs">
                                            <div class="input-custom">
                                                <input value="" type="text" name="meta_title" class="form-control">
                                                <span class="input-span">عنوان الميتا</span>
                                            </div>
                                            <div class="input-custom">
                                                <input value="" type="text" name="meta_keywords" class="form-control">
                                                <span class="input-span">الكلمات الدلالية</span>
                                            </div>
                                            <div class="input-custom">
                                                <textarea name="meta_description" class="form-control editor"></textarea>
                                                <span class="input-span">وصف الميتا</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button class="btn ripple btn-primary" type="submit"><i class="fe fe-save"></i> حفظ</button>
                        </div>
                    </div>
                </form>

            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->
@endsection
@push('js')

@endpush

resources/views/dashboard/umras/edit.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">

                <form action="{{route('umras.update',$umra->id)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="card">
                        <div class="card-header">
                            <h3>تعديل عمره</h3>
                        </div>
                        <div class="card-body pb-0">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input value="{{$umra->name}}" type="text" name="name" class="form-control">
                                        <span class="input-span">اسم العمره</span>
                                    </div>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <textarea name="details" rows="3" class="form-control editor">{{$umra->details}}</textarea>
                                        <span class="input-span">تفاصيل العمره</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input type="date" value="{{$umra->start_at}}" name="start_at" class="form-control">
                                        <span class="input-span">تاريخ الانطلاق</span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input type="number" min="0" value="{{$umra->price}}" name="price" class="form-control">
                                        <span class="input-span">سعر العمره</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <label class="">الصورة ( مقاس الصورة -- 750 طول * 1660 عرض )</label>
                                        <input id="photo" type="file" name="photo">
                                        <img width="100" id="preview" height="100" src="{{$umra->image}}" alt="">
                                    </div>

                                </div>


                            </div>

                            <div class="accordion-container">
                                <div class="set">
                                    <a href="#">
                                        بيانات السيو SEO
                                        <i class="fa fa-plus"></i>
                                    </a>
                                    <div class="box-custom">
                                        <div class="flex-divs">
                                            <div class="input-custom">
                                                <input value="{{$umra->meta_title}}" type="text" name="meta_title" class="form-control">
                                                <span class="input-span">عنوان الميتا</span>
                                            </div>
                                            <div class="input-custom">
                                                <input value="{{$umra->meta_keywords}}" type="text" name="meta_keywords" class="form-control">
                                                <span class="input-span">الكلمات الدلالية</span>
                                            </div>
                                            <div class="input-custom">
                                                <textarea name="meta_description" class="form-control editor">{{$umra->meta_description}}</textarea>
                                                <span class="input-span">وصف الميتا</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button class="btn ripple btn-primary" type="submit"><i class="fe fe-save"></i> حفظ</button>
                        </div>
                    </div>
                </form>

            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->
@endsection


@push('js')

@endpush

resources/views/dashboard/umras/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">
                <div class="card">
                    <div class="card-header">
                        <h3>العمره</h3>
                        <div class="flex-btns">
                            <a href="" id="delete_all_btn" class="btn ripple btn-danger d-none"><i class="fe fe-trash"></i> حذف الكل </a>
                            <a href="{{route('umras.create')}}" class="btn ripple btn-primary"><i class="fe fe-plus"></i> اضافة </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <form id="bulk_delete" action="{{route('umras.bulkDelete')}}" method="post">
                                @csrf
                                <table class="table datatable table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>
                                            <input type="checkbox" id="check_all">
                                        </th>
                                        <th>#</th>
                                        <th>العنوان</th>
                                        <th>تاريخ الانطلاق</th>
                                        <th>العمليات</th>
                                    </tr>
                                    </thead>


                                    <tbody>


                                    </tbody>

                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->

@endsection
@push('js')
    <script>
        var table = $('.table.datatable').DataTable({
            lengthChange: true,

            "processing": true,
            "serverSide": true,
            "ajax": {
                url: '{{route('umras.data')}}',
            },
            "columns": [
                {data: 'check_item', name: 'check_item', sortable: false, searchable: false},
                {data: 'id', name: 'id'},
                {data: 'name', name: 'name'},
                {data: 'start_at', name: 'start_at'},
                {data: 'actions', name: 'actions'}
            ]
        });

    </script>
@endpush